@startuml
[IApplicationBuilder]
[Build]
[Configure]
[IApplication]
[Start]
[Run]
[Stop]

[IApplicationBuilder] -> [Build]
[Build] -> [Configure]
[Configure] -> [IApplication]
[IApplication] -> [Start]
[IApplication] --> [Run]
[Run] --> [Stop]
[Start] -> [Stop]
@enduml